repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ^treeno/grammar/gen/
    -   id: trailing-whitespace
        exclude: ^treeno/grammar/gen/
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: ['-l 80']
        exclude: ^treeno/grammar/gen/
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        exclude: ^treeno/grammar/gen/
