import re

# These autogenerated python files are huge and add a lot of overhead to the doctest scans
DONT_DOCTEST_PATH = re.compile(r"treeno\/grammar\/gen\/.*\.py")


def pytest_ignore_collect(path):
    if DONT_DOCTEST_PATH.search(path.strpath):
        return True
