name: tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, 3.10-dev ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install pytest flake8
    - name: Install library
      run: |
        python -m pip install .
    - name: Lint
      run: |
        flake8 . --exclude treeno/grammar/gen
    - name: Run tests
      run: |
        python -m pytest tests
